kind: Service
apiVersion: v1
metadata:
  name: nano-metrics
  namespace: default
  annotations:   
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8501"
#spec:
#  type: ExternalName
#  externalName: test03.infragravity.com
spec:
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501